Repository validator-labs/validator-plugin-kubescape, pull requests merged in 2024-12, with the labels that each got.

#76 chore(main): release 0.0.5
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-kubescape/Chart.yaml
  chart/validator-plugin-kubescape/README.md
  chart/validator-plugin-kubescape/values.yaml
Labels: autorelease: pending, size:M, lgtm

#111 fix: metrics targetPort https -> 8443
  chart/validator-plugin-kubescape/README.md
  chart/validator-plugin-kubescape/values.yaml
Labels: size:XS, lgtm

#110 chore(main): release 0.0.6
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-kubescape/Chart.yaml
  chart/validator-plugin-kubescape/README.md
  chart/validator-plugin-kubescape/values.yaml
Labels: autorelease: pending, size:S
